version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - spring-mysql-net

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"  # 외부 포트를 3307로 변경
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-mysql-net

volumes:
  mysql-data:

networks:
  spring-mysql-net:
    driver: bridge